### ISSUE TITLE
Bug: mapdql  strtok() on input processing loop is destructive to mapdql command history

### ISSUE THREAD

**Issue by ptumati** [heavyai/heavydb#169]
Launch mapdql, press up for command line history.  If your command is one of the commands that uses strtok(), the destructive modification of 'line' tampers with what gets placed in the history.  (Pull request #147 corrects this problem also (for commands converted to that system) -- although if that request is rejected, this bug remains.) 

Example:

> mapdql> \cpu x y z
> 
> Then <press up>
> 
> You correctly see:
> 
> mapdql> \cpu x y z

Now do this for \copygeo:

> mapdql> \copygeo x y
> File does not exist: x
> 
> [press up]
> mapdql> \copygeo x

^ The y is dropped, even though y is the second parameter required (table name.)

And \copy:

> mapdql> \copy x y
> File does not exist.
> [press up]
> mapdql> \copy x
>

**Comment by randyzwitch** [comment]
Appears this was fixed elsewhere, closing. If I'm mistaken, we can re-open

**Comment by ptumati** [comment]
I think this is still a problem.  Some commands were moved to an input-tokenizing system, but there are a bunch of old commands that are still doing their own thing.  It's probably low priority, but it's a real bug.  Probably best to leave open.

**Comment by psilvest** [comment]
This issue has been inactive for a while, and the project has changed substantially. If this still occurs on the latest release, please add reproduction steps and environment details.
